name: Release

on:
  push:
    branches:
      - master

jobs:
  dappnode-release:
    name: Release new version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installing dappnodesdk and publishing package
      run: |
        sudo npm install -g @dappnode/dappnodesdk
        sudo GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} dappnodesdk publish patch -p infura --dappnode_team_preset
