name: Update Manifest file

on:
    repository_dispatch:
      types: dappnode_update

jobs:
  dappnode-update:
    name: Update Manifest file
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cloning nethermind repo and fetching latest tag
      run: |
        git clone https://github.com/NethermindEth/nethermind.git
        cd nethermind/ && git describe --tags > git-tag
    - name: Updating package and Nethermind versions
      run: |
        GIT_TAG="$(tail nethermind/git-tag)"
        VER="$(sed -n '3p' dappnode_package.json)"
        VERSION=${VER:14:-2}
        VERSION_UPDATED="$(./semver-update.sh patch $VERSION)"
        sed -i "3s/.*/  \"version\": \"${VERSION_UPDATED}\",/" dappnode_package.json
        sed -i "4s/.*/  \"upstreamVersion\": \"v${GIT_TAG}\",/" dappnode_package.json
        rm -rf nethermind/
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update manifest
        body: |
          Manifest file has been updated.
          - Files included - dappnode_package.json
          - Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        title: 'Updating Manifest file'
        labels: manifest
        author-name: github-actions[bot]
        author-email: 41898282+github-actions[bot]@users.noreply.github.com
        committer-name: GitHub
        committer-email: noreply@github.com
        branch: manifest-update
        branch-suffix: short-commit-hash
        base: master
    - name: Checking Outputs
      run: |
        echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"


