name: Release

on:
  push:
    branches:
      - master

jobs:
  dappnode-release:
    name: Release new version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installing dappnodesdk
      run: npm install -g @dappnode/dappnodesdk
    - name: Publishing dappnode package
      run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} dappnodesdk publish patch -p infura --dappnode_team_preset
